#---------------------------------# 
#      environment configuration  # 
#---------------------------------# 
os: WMF 5
version: 1.0.0.{build}
install: 
  - cinst -y pester

#---------------------------------# 
#      build configuration        # 
#---------------------------------# 

build: false

#---------------------------------# 
#      test configuration         # 
#---------------------------------# 

test_script:
    - ps: |
        $testResultsFile = ".\TestsResults.xml"
        $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        if ($res.FailedCount -gt 0) { 
            throw "$($res.FailedCount) tests failed."
        }
    
#---------------------------------# 
#      deployment configuration   # 
#---------------------------------# 

# scripts to run before deployment 
deploy_script: 
  - ps: |
      # Creating project artifact
      $buildFolder = $ENV:APPVEYOR_BUILD_FOLDER
      $StagingFolder = Join-Path -Path $buildFolder -ChildPath 'Staging'
      $null = New-Item -Path $StagingFolder -Type directory
      $ModuleFolder = Join-Path -Path $StagingFolder -ChildPath 'LoopbackAdapter'
      $null = New-Item -Path $ModuleFolder -Type directory
      $VersionFolder = Join-Path -Path $ModuleFolder -ChildPath $ENV:APPVEYOR_BUILD_VERSION
      $null = New-Item -Path $VersionFolder -Type directory
      
      # Populate Version Folder
      $null = Copy-Item -Path (Join-Path -Path $buildFolder -ChildPath 'LoopbackAdapter.*') -Destination $VersionFolder
      $null = Copy-Item -Path (Join-Path -Path $buildFolder -ChildPath 'LICENSE') -Destination $VersionFolder
      $null = Copy-Item -Path (Join-Path -Path $buildFolder -ChildPath 'README.MD') -Destination $VersionFolder

      # Set version number
      $manifest = Join-Path -Path $VersionFolder -ChildPath "LoopbackAdapter.psd1"
      (Get-Content $manifest -Raw).Replace("1.0.0.0", $env:APPVEYOR_BUILD_VERSION) | Out-File $manifest
      
      # Create zip artifact
      $zipFilePath = Join-Path -Path $StagingFolder -ChildPath "${env:APPVEYOR_PROJECT_NAME}_${env:APPVEYOR_BUILD_VERSION}.zip"
      $null = Add-Type -assemblyname System.IO.Compression.FileSystem
      [System.IO.Compression.ZipFile]::CreateFromDirectory($StagingFolder, $zipFilePath)
      
      # Remove Staging Folder
      $null = Remove-Item -Path $StagingFolder -Recurse -Force
            
      # Create Publish Script Artifact
      $PublishScriptName = $env:APPVEYOR_PROJECT_NAME + "." + $env:APPVEYOR_BUILD_VERSION + "_publish.ps1"
      $PublishScriptPath = Join-Path -Path $buildFolder -ChildPath $PublishScriptName
      Set-Content -Path $PublishScriptPath -Value "Publish-Module -Name 'LoopbackAdapter' -RequiredVersion ${env:APPVEYOR_BUILD_VERSION} -NuGetApiKey (Read-Host -Prompt 'NuGetApiKey')"
      
      @(
          # You can add other artifacts here
          $zipFilePath,
          $PublishScriptPath
      ) | % { 
          Write-Host "Pushing package $_ as Appveyor artifact"
          Push-AppveyorArtifact $_
      }
        


